### ISSUE TITLE
_pre_delete_hook not being called

### ISSUE THREAD

**Issue by neurino** [kkinder/NdbSearchableBase#1]
Hello,

I find in my search index elements I have successfully deleted from the datastore.

So it seems `SearchableModel._pre_delete_hook` isn't being called when I do `entity.key.delete()`

[Is it related to this topic?](https://stackoverflow.com/questions/23921653/delete-hooks-in-ndb-polymodel-childclass-wont-execute)

BTW, thanks for your work, apart from this it works like a charm.

**Comment by neurino** [comment]
More on this, I checked the model and it has its own `_pre_delete_hook` 

Calling `SearchableModel._pre_delete_hook(key)` in it solved the issue.

In short, no issue with NdbSearchableBase, here the final code

```
class Account(SearchableModel, ndb.Model):
    name = ndb.StringProperty(required=True)
    vat_id = ndb.StringProperty(required=True)
    head_office = ndb.KeyProperty(kind=Address)
    ...
    
    @classmethod
    def _pre_delete_hook(cls, key):
        _delete_all_children(cls, key)
        SearchableModel._pre_delete_hook(key)
```

**Comment by neurino** [comment]
See above comment, no issue, please close this.

**Comment by kkinder** [comment]
Hmmm, I do want to make sure this isn't a bug. Was it just that you were providing your own `_pre_delete_hook` and it wasn't calling the super-classes's `_pre_delete_hook`?

**Comment by neurino** [comment]
Yes, my code was the one above without last line.
